<title>CRISPOR - TEFOR&#39;s CRISPR ONLINE TOOL</title>
<meta name='description' content='Design your Cas9 RNA guide and control the off-targets. http://tefor.net/crispor CRISPOR - CRISPr selectOR - is a program that helps design and evaluate target sites for use with the CRISPR/Cas9 system. It uses the BWA algorithm to identify guide RNA sequences for CRISPR mediated genome editing. It searches for off-target sites (with and without mismatches), shows them in a table and annotates them with flanking genes.  CRISPOR currently includes more than 70 genomes ! To add your genome of interest, contact the CRISPOR web site manager: penigault@tefor.net.'/>
<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
<meta property='fb:admins' content='692090743' />
<meta property='og:title' content='CRISPOR - TEFOR&#39;s CRISPR ONLINE TOOL' />
<meta property='og:description' content='Design your Cas9 RNA guide and control the off-targets. http://tefor.net/crispor CRISPOR - CRISPr selectOR - is a program that helps design and evaluate target sites for use with the CRISPR/Cas9 system.  It uses the BWA algorithm to identify guide RNA sequences for CRISPR mediated genome editing. It searches for off-target sites (with and without mismatches), shows them in a table and annotates them with flanking genes.  CRISPOR currently includes more than 70 genomes ! To add your genome of interest, contact the CRISPOR web site manager: penigault@tefor.net.'/>
<meta property='og:type' content='website' />
<meta property='og:url' content='http://tefor.net/crispor/crispor.cgi' />
<meta property='og:image' content='http://tefor.net/crispor/image/CRISPOR.png' />

<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js'></script>
<script src='https://apis.google.com/js/platform.js' async defer></script>
<script src='http://code.jquery.com/ui/1.11.1/jquery-ui.min.js'></script>

