<div id='navi'>
        <div id='menu' class='default'>
                <ul class='navi'>
                <li><a href='http://tefor.net'>Home</a></li>
                <li><a href='./crispor.cgi'>CRISPOR</a></li>
                <li><a href='http://tefor.net/main/pages/citations'>Citations</a></li>
                <li><a href='http://tefor.net/main/pages/blog'>News</a></li>
                <li><a href='http://tefor.net/main/pages/events'>Events</a></li>
                <li><a href='http://tefor.net/main/pages/partners'>Partners</a></li>
                <li><a href='http://tefor.net/main/pages/contacts'>Contacts</a></li>
                </ul>
        </div>
</div>
