<div class="networking_panel">
    <div class="fb-like"
         data-href="crispor.cgi"
         data-layout="box_count"
         data-action="like"
         data-show-faces="false"
         data-share="false">
    </div>
    <br>
    <br>
    <div class="g-plusone" data-href="crispor.cgi" data-size="tall"></div>
    <br>
    <br>
    <a href="https://twitter.com/share" 
       class="twitter-share-button" 
       data-count="vertical" data-dnt="true">Tweet</a>
    <script type="text/javascript">
    window.twttr=(function(d,s,id){var t,js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return}js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);return window.twttr||(t={_e:[],ready:function(f){t._e.push(f)}})}(document,"script","twitter-wjs"));
    </script>
    <br>
    <br>
    <a target="_blank" href="https://groups.google.com/forum/?hl=en#!forum/crispor">CRISPOR<br>forum</a>
    
    <br>
    <a href="#footer-credits" onclick="$('#footer-credits').fadeToggle('fast');">
        <img src="image/info.png" class="infopoint" >
        <br>
        credits
    </a>    
    <br>
</div>
