<div style='margin-top:20px;margin-bottom:10px;color:gray;font-size:medium;border-bottom:solid thin grey;'>
    Sponsored by:
</div>

<!--title="Buy Cas9 Nuclease protein, S. pyogenes"--> 
<div class="sponsors">
        
    <!--<a onmouseenter="$('#nebtext').show();" target="_blank" href="http://international.neb.com/products/m0386-cas9-nuclease-s-pyogenes">-->
    <a target="_blank" href="http://international.neb.com/products/m0386-cas9-nuclease-s-pyogenes">
        <img style="width:225px;margin-right:50px;" src="image/NEBlogo.png">
    </a>

    <a target="_blank" href="http://www.idtdna.com/crispr">
        <img style="width:225px;margin-top:25px;" src="image/IDTlogo.png">
    </a>
    
</div>

<style>
      
   div.sponsors:hover
   {
        -webkit-animation-play-state: paused;
        opacity:1;
   }   
   div.sponsors a
   {
       float:right;
       margin-right:50px;
   }
   
   div.sponsors
   {          
       /*border: solid thin red;*/
       /*display:inline-block;*/
       -webkit-animation:           mymove 2s infinite; /* Chrome, Safari, Opera */
       -webkit-animation-direction: alternate; /* Chrome, Safari, Opera */

       animation:           mymove 2s infinite;        
       animation-direction: alternate;
   }
   /* Chrome, Safari, Opera */
   @-webkit-keyframes mymove
   {
       from
       {                
           opacity: 0.7;
       }
       to   
       {             
           opacity: 1;
       }
   }
   /* Standard syntax */
   @keyframes mymove
   {
       from
       {                
           opacity: 0.7;
       }
       to   
       {             
           opacity: 1;
       }
   }

</style>
