#!/bin/bash
set -e
db=$1
outdir=$2

if [ "$db" == "" ] && [ "$outDir" == "" ]; then
    echo usage: downloadGenome genomeCode outputFolder
    echo Downloads pre-indexed and annotated genome from crispor.tefor.org
    echo Example genome codes are: hg19, mm10, sacCer3 etc.
    echo For full list of codes, see: http://crispor.tefor.net/genomes/genomeInfo.all.tab
    exit
else
   if [ "$outDir" == "" ]; then
       outDir=/var/www/html/genomes
       mkdir -p $outDir
   fi
    wget -r -nH --cut-dirs=2 --no-parent --reject="robots.txt" --reject="index.html*"  crispor.tefor.net/genomes/$db/ -P $outDir/$db
fi
